name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup go environment
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'

    - name: Build
      run: go build ./...

    - name: Run unit tests
      run: go test -v

    - name: Run linter
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
